name: lectures
channels:
  - pytorch
  - defaults
dependencies:
  - ipykernel=6.19.2
  - ipython=8.10.0
  - jupyter=1.0.0
  - jupyterlab=3.5.3
  - matplotlib=3.7.1
  - networkx=2.8.4
  - notebook=6.5.2
  - numpy=1.23.5
  - pandas=1.5.3
  - pillow=9.4.0
  - pip=23.0.1
  - python=3.10.9
  - pytorch=2.0.0
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - torchvision=0.15.0
  - pip:
      - mpmath==1.2.1
      - notexbook-theme==2.0.1
